- controls/V-72433.rb
Pulled the conditional impact statements out of the if/then construct
early on and added them to the corresponding section near the
corresponding describe blocks.
- Fixes #16
> Reorganized logic for V-72433

- controls/V-71965.rb
Pulled the conditional impact statements out of the if/then construct
early on and added them to the corresponding section near the
corresponding describe blocks.
- Fixes #18
> Reorganized logic for V-71965

- controls/V-81019.rb
Added logic to allow the control to insensitively match the
prescribed values. This is the behavior of audisp.
- Fixes #21
> Updated V-81019 to correctly match configurations

- controls/V-72223.rb
The control was comparing os_env('value').content to an integer.
os_env('value'}.content returns a string. Updated to convert the
string to an integer (to_i). The output of doing this directly was
poor so I added an explicit subject to clean up the output.
- Fixes #27
> Resolved datatype comparison issue in V-72223

- controls/V-72417.rb
Pulled the conditional impact statements out of the if/then construct
early on and added them to the corresponding section near the
corresponding describe blocks.
- Fixes #17
> Reorganized logic for V-72417

- controls/V-72089.rb
- Removed the `@` symbol from the `#{audit_log_dir}` variable causing
it to resolve to `nil` and presenting all system partitions.
- Update the shell call to `df` to use standard 1K blocksize instead
of human readable format which can return results with various units.
- Update the space calculation to convert KB into MB ( / 1024) instead
of converting [assumed] GB into MB ( * 1024).
- Fixes #32
> Adjusted calculation logic in V-72089

- controls/V-71863.rb
Added variable definition via input (banner_message_text_cli).
Added variable definition via input (banner_message_text_cli_limited).
- Fixes #34
> Resolved `undefined local variable` in V-71863

- controls/V-71933.rb
Added a variable definition via input (min_reuse_generations).
- Fixes #35
> Fixed `undefined variable` error for V-71933

- controls/V-78995.rb
Removed the switch 'skip_deprecated_controls' from the control.
Restored 'traditional' if/then structure and located the 'impact'
override in the fallthrough case.
- Fixes #3
> Remove faulty logic from V-78995

- controls/V-72217.rb
- inspec.yml
Added the functionality of collecting all configuration files under
limits.d. These files are then searched for any global ('*') entries
matching 'hard' and 'maxlogins'. Any file matching but having a
value of anything other than '10' fails.
- Fixes #23
> Consider limits.d when checking for hard maxlogins

- controls/V-72213.rb
- inspec.yml
Update the control to take a switch/boolean input that specifies
whether a non-nails solution is in use. If it is, require that
a description of the solution be input as a way to document
the solution
- Fixes #24
> Allow customization of the A/V solution in use.

- controls/V-71963.rb
- inspec.yml
- Added a check to see if the EFI configuration file exists. If not,
this becomes NA.
- Added a check for minor version of the OS. If 7.2 or later we only
allow 'root' as a superuser.
- The STIG guidance states that this is NA for versions after 7.2.
However, it seems clear that this is still needed it just changes
the way we enforce it.
- Removed 'efi_user_boot_files'  input as it doesn't matter what file
the configuration comes from, only that it is merged into the main
config.
- Removed 'efi_main_cfg' input since we need to make the path dynamic to
support RHEL variants such as CentOS. Also, the EFI path is pretty
well static.
- Fixes #40
> Updated V-71963 to be NA when EFI not in use

- controls/V-72171.rb
- Removed the architecture check for path watches.
-  Removed all check for '/bin/mount' as this path is not used.
- Fixes #29
> Corrected the tests for V-72171

- controls/V-72073.rb
- inspec.yml
- Simplified logic to remove loop searching for 'sha512' entries.
Instead return them directly with the 'where' clause.
- Provide an input array to contain patterns to exclude from the test.
- Fixes #36
> Updated V-72073 to support overrides

- controls/V-72065.rb
- Allow /tmp to be specified in /etc/fstab as well as with the tmp.mount
service.
- Validate that there is only one entry for /tmp in fstab
- Ensure that the device_name is not empty for the mount
- Fixes #37
> Updating V-72065 to account for fstab entry

- controls/V-71897.rb
- inspec.yml
- Per v2r6 of the DISA STIG `tmux` is now an allowable option along with
screen.
- Add an input list to contain `screen` and `tmux` and to support any
future options.
- Fixes #67
> Update V-71897 to allow multiple multiplexers

- controls/V-71937.rb
- If ac (authconfig) files are included or substacked by other services
they will still be checked.
- Loop over each service file in /etc/pam.d to provide a complete view
of the configuration.
- Fixes #41
> Modify V-71937 to ignore `*-ac` files

- controls/V-72001.rb
- inspec.yml
- The STIG control asks to validate that all accounts present on the
system are approved. Explicilty adding them to a known user list
provides that validation.
- There doesn't seem to be a need for a 'disallowed_users' list as users are
implicitly disallowed by not being explicitly allowed.
- Use 'expect' syntax to allow for finer control over the reporting
output. Previous output displayed a list of users for each line. Now we
just show that each user listed in /etc/passwd has been explicitly
listed as an approved user.
- Fixes #39
> Updating V-72001 to validate all `allowed_users`

- inspec.yml
- Updated inspec.yml to remove any arrays or hashes with enclosing
brackets.
- The only time brackets are used is when an empty array ([]) or hash
({}) needs  to be represented
- Fixes #84
> Modified inspec.yml to use `block` style

- controls/V-71947.rb
- This control was not splitting output lines into an array and was
matching ALL lines containing 'NOPASSWD', which included commented
lines.
- Modified to use the `file` resource to be more OS agnostic and build
a results array of uncommented lines containing 'NOPASSWD'
- Reporting is improved for readability
- Fixes #90
> Fixed reporting for V-71947

- controls/V-81005.rb
- Only OS versions earlier than 7.2 should be checked. Was checking any
version 7.2 and later.
- Fixes #91
> Correct logic in V-81005

- controls/V-72219.rb
- inspec.yml
- Changed `firewalld_ports_deny` to a Hash instead of Array
- Cast hash references to symbols for proper resolution
- Fixes #28
> Fixed issues in V-72219

- controls/V-72257.rb
- Removed multiple individual tests and replaced with
'be_more_permissive_than' which covers all permission sets.
- Changed the command to return key files to stop filtering by current
permissions. Inspec should validate the permissions in tests. We need
pre-filter results outside of tests.
- Fixes #97
> Updated V-72257

- controls/V-71855.rb
- Added input call for `rpm_verify_integrity_except`
- Fixes #103
> Fixed bug in V-71855
